### ISSUE TITLE
Python Version 

### ISSUE THREAD

**Issue by haamoon** [lucfra/FAR-HO#1]
Hi, 

Thanks for providing the code. It is well written and very easy to use. I was wondering which version of Python and Tensorflow you used for testing?

**Comment by lucfra** [comment]
Hi hammon, thank you very much!

I've written it with Python 3.5.3 and Tensorflow 1.2. I aslo tested it with Python 3.6 and Tensorflow 1.4. With Tensorflow 1.3 there might be some problems with the computation of some second order derivatives (which hoverer, seems to be solved with 1.4).
