### ISSUE TITLE
Support for python ver==2.x or at least ver >= 2.7.x

### ISSUE THREAD

**Issue by habibrk** [lucfra/FAR-HO#4]
Can you please provide support for python 2.7.x ?

**Comment by lucfra** [comment]
Hi habibrk. 
We'll work on it in the next days.

Cheers,
Luca

**Comment by lucfra** [comment]
I added support for python 2.7 and did some test with tensorflow (without gpu).
Everything in the main package should work.

Let me know if it also works for you!

Luca

**Comment by habibrk** [comment]
@lucfra thanks for the prompt reply/action, MNIST example worked with python 2.7.5 and tensorflow 1.4.1 ...
