### ISSUE TITLE
Some questions regarding Forward-HO?

### ISSUE THREAD

**Issue by habibrk** [lucfra/FAR-HO#6]
I really don't get https://github.com/lucfra/FAR-HO/blob/master/far_ho/hyper_gradients.py#L351, why was it needed?

Aren't we already getting the hyper-gradient at https://github.com/lucfra/FAR-HO/blob/master/far_ho/hyper_gradients.py#L349

Also, please explain if this step is really needed as I don't see it explicitly stated in your paper, thanks.

**Comment by lucfra** [comment]
Hi habibrk,
sorry for the delayed answer, I've been away these days!

So, this package is a follow up of https://github.com/lucfra/RFHO which was directly connected to the paper and, as such, contains some (minor) generalization. The one that you pointed out is about the fact that here we allow the outer objective to _explicitly_ depends upon \lambda which is generally E=E(w, \lambda). This is in contrast to the paper in which we considered only outer objectives (validation errors) which could _implicitly_ depend on \lambda.
If there is explicit dependence then the hypergradient will be given by
\nabla_\lambda E = \partial_w E d w/ d \lambda +\partial_\lambda E

Sorry for the poor writing but I couldn't find an easy way to render latex here.  

The line that you mention (now 
https://github.com/lucfra/FAR-HO/blob/master/far_ho/hyper_gradients.py#L359) check if there is an explicity dependence and if so adds to the hypergradient the appropriate term.

I added some comments on the code and will shortly add another reference to a more recent work.

Hope this helps, 
Cheers, 
Luca
